mindmap
    root((Ingeniería en Software))
        ¿Qué es Ingeniería?
            Innovar soluciones
            Ingenio en el desarrollo
        ¿Qué es Software?
            Sistematizar Programas
            Crear sistemas para soluciones
        ¿Qué es Ingeniería en Software?
            Solucionar problemas mediante programas digitales
            Estudio de bases datos del sistemasmindmap
